### ISSUE TITLE
Question about dependency between old hotfixes

### ISSUE THREAD

**Issue by mauritsvanrees** [jone/plone-hotfixes#1]
This is a very helpful page. Thank you very much!

A question: two hotfixes are listed as "Only required when Products.PloneHotfix20110720 is not installed": Products.PloneHotfix20110531 and Products.Zope_Hotfix_CVE_2010_1104. Where did you get that information?  I do not see it anywhere.

**Comment by jone** [comment]
The information is from our internal company wiki - but I should have verified it more carefully.

## 

#### Products.Zope_Hotfix_20110622

The note on the hotfixes page was:

> Only required when Products.PloneHotfix20110720 is **not** installed

It was based on pypi page ( https://pypi.python.org/pypi/Products.Zope_Hotfix_20110622 ), which says:

> Any version of Zope 2.10 or Zope 2.11 where PloneHotfix20110720 is installed (Plone 3.0, 3.1, 3.2 and 3.3 <= 3.3.5).

There are 2 problems:

1) The note on the hotfixes page above should not contain the `not` - this was a typo :-(
2) The note on the pypi page only refers to Plone 3.x, but the patch is also required for 4.x

I've therefore decided to remove the note altogether - do you agree?

## 

#### Products.Zope_Hotfix_CVE_2010_3198

The pypi page of PloneHotfix20110928 says it includes Zope_Hotfix_CVE_2011_3587, but nothing about Zope_Hotfix_CVE_2010_3198.
I'm therefore not sure whether this information is a typo and whether it is accurate.
Since I'm not sure I've removed this note too.

**Comment by mauritsvanrees** [comment]
Thanks for verifying and fixing.
